# Generated by Django 2.1.2 on 2018-11-05 11:14

import cms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0015_auto_20181105_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='poster_height',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='poster_width',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='source',
            field=models.FileField(blank=True, upload_to='cms/%Y_%m', validators=[cms.models.validate_video_type], height_field='poster_height', width_field='poster_width'),
        ),
    ]
